### ISSUE TITLE
Submit a goal

### ISSUE THREAD

**Issue by nthnjustice** [PowerShareInternational/powershare-medford-ma#10]
@PowerShare 

I'm assuming we want to vet goal submissions from voters. Is there an email address you'd like those to be forwarded to?

**Comment by PowerShare** [comment]
Thanks, Nathan. You are right, and please have those forwarded to powershare.community@gmail.com. Thanks!

**Comment by nthnjustice** [comment]
Discuss goal submission:

a) email - not secure & easy to abuse
b) admin panel - external db, light interface, difficult approval api
